name: Generar Firma y Compilar APK Release

on:
  push:
    branches: [ "main" ] # Cambia a tu rama principal si es diferente
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el código del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java de Android (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Configurar Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.4'

    - name: Generar Clave de Firma Automáticamente
      run: |
        keytool -genkeypair \
          -v \
          -keystore mobile/app/release-auto-key.jks \
          -alias my-auto-alias \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass mi_contrasenia_secreta \
          -keypass mi_contrasenia_secreta \
          -dname "CN=WowMobile, OU=Dev, O=Client, L=City, S=State, C=US"

    - name: Compilar APK (Release)
      run: gradle assembleRelease
      working-directory: mobile

    - name: Subir APK generado y firmado
      uses: actions/upload-artifact@v4
      with:
        name: app-release-firmado-auto
        path: mobile/app/build/outputs/apk/release/app-release.apk
